version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

commands:
  build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
            # - deps-clear
      - run:
          name: Install Dependencies
          command: |
            poetry install --no-interaction
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          # key: deps-clear
          paths:
            - /root/.cache/pypoetry/virtualenvs
            - /root/.cache/.tox

  linting:
    steps:
      - run:
          name: Run flake8
          command: |
            poetry run flake8 .
      - run:
          name: Run black formatting check
          command: |
            poetry run black --diff --check .

executors:
  py36-executor:
    docker:
      - image: circleci/python:3.6
  py37-executor:
    docker:
      - image: circleci/python:3.7
  py38-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-with-py36:
    executor: py36-executor
    filters:
      branches:
        ignore:
          - "gh-pages"
    steps:
      - build
      - linting
      - run:
          name: Run tox py36
          command: |
            poetry run tox -e py36
  build-with-py37:
    executor: py37-executor
    filters:
      branches:
        ignore:
          - "gh-pages"
    steps:
      - build
      - linting
      - run:
          name: Run tox py37
          command: |
            poetry run tox -e py37
  build-with-py38:
    executor: py38-executor
    filters:
      branches:
        ignore:
          - "gh-pages"
    steps:
      - build
      - linting
      - run:
          name: Running tests py38
          command: |
            poetry run pytest --cov-report=xml --cov=gns3fy tests/
      - codecov/upload:
          file: coverage.xml

workflows:
  py36-test:
    jobs:
      - build-with-py36
  py37-test:
    jobs:
      - build-with-py37
  py38-test:
    jobs:
      - build-with-py38
