version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - "gh-pages"


orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      # - image: circleci/python:3.7
      - image: continuumio/miniconda3
    steps:
      - checkout
      - restore_cache:
          keys:
            # - deps-{{ checksum "poetry.lock" }}
            - deps-clear
      - run:
          name: Install curl
          command: |
            apt-get update
            apt-get install curl -y
      - run:
          name: Install Poetry
          command: |
            pip install poetry
            poetry config virtualenvs.create false
      - run:
          name: Install Dependencies
          command: |
            poetry install --no-interaction
      - run:
          name: Run flake8
          command: |
            poetry run flake8 .
      - run:
          name: Run black formatting check
          command: |
            poetry run black --diff --check .
      - run:
          name: Run tox
          command: |
            poetry run tox
      - save_cache:
          # key: deps-{{ checksum "poetry.lock" }}
          key: deps-clear
          paths:
            - /root/.cache/pypoetry/virtualenvs
            - /root/.cache/.tox
      - run:
          name: Running tests
          command: |
            poetry run pytest --cov-report=xml --cov=gns3fy tests/
      - codecov/upload:
          file: coverage.xml
